"""initial schema (baseline created from ORM metadata)

Revision ID: 0001_initial
Revises:
Create Date: 2024-06-01

This baseline migration creates the full schema from the ORM metadata. Subsequent schema changes
should be authored as incremental migrations (autogenerated against Postgres).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from app.models import Base

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
